<a href="https://colab.research.google.com/github/faizan1402/Natural_Language_Processing/blob/main/introduction_to_deep_learning_nlp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

'''Section Goals

    -> Understand basic overview of deep learning
    -> Understand basics of LSTM and RNN
    -> Use LSTM to generate text from source corpus
    -> Create QA chat bots with python.'''

'Section Goals\n\n    -> Understand basic overview of deep learning\n    -> Understand basics of LSTM and RNN\n    -> Use LSTM to generate text from source corpus\n    -> Create QA chat bots with python.'

In [ ]:
'''-> Deep Learning
-> Before we launch straight into nural networks,we need to understand the individual componets first,such as a single "neuron"
-> Artificial Neural Networks(ANN) actually have a basis in biology
-> Let's see how we can attempt to mimic biological neurons with an artificial neuron,known as a perceptron!
-> The AI neuron also input outputs!
   Input 0 -
              -> Output
   Input 1 -'''



In [ ]:
'''Deep Learning
   Review ->
   -> Biological Neuron
   -> Perceptron Model
   -> Mathematical Representation .'''

'Deep Learning\n   Review ->\n   -> Biological Neuron\n   -> Perceptron Model\n   -> Mathematical Representation .'

#**Introduction To Neural Networks**

In [ ]:
'''Welcome to the section on deep learning! We'll be using Keras with a TensorFlow backend to perform our deep learning operations.

This means we should get familiar with some Keras fundamentals and basics!'''

In [ ]:
'''We have seen how a single perception behaves,now let's expand this concept to the idea of neural network!
-> Let's see how to connect many perceptrons together and then how to represent this mathematically!'''

'''1-> Input Layers
  -> Real values from the data
  2-> Hidden Layers
   -> Layers in between input and output
   -> 3 or more layers is deep network
   3 -> Output Layer
      -> Final estimate of the output'''

In [ ]:
'''As we go forward through more layers the level of abstraction increases.
  -> Let's now discuss the activation function in a little more detail!.'''

In [ ]:
# Now that we understand the basics of neural theory,let's move or implementing and building our own neural network models with keras!

In [ ]:
''' -> Let's learn how to create a very simple neural network for classifying the Iris data set!
    -> The iris data set contains measurements of flower petals and sepals and has
    corresponding labels to one of three classes (3 flower species).

#**DataSet**

In [ ]:
#We will use the famous Iris Data set.
#More info on the data set: https://en.wikipedia.org/wiki/Iris_flower_data_set
#Reading in the Data Set
#We've already downloaded the dataset, its in this folder. So let's open it up.

In [ ]:
import numpy as np
from sklearn.datasets import load_iris

In [ ]:
iris = load_iris()

In [ ]:
type(iris)

sklearn.utils.Bunch

In [ ]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [ ]:
X = iris.data
X
#[5.1, 3.5, 1.4, 0.2] ->[sepal_length,sepal_width,petal_length,petal_width]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [ ]:
y = iris.target
y
#class 0,class 1,class 2 labal

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
#class 0 --> [1,0,0] (index ->0)
# class 1 --> [0,1,0] (index ->1)
# class 2 --> [0,0,1] (index ->2)

In [ ]:
from keras.utils import to_categorical
y = to_categorical(y)

In [ ]:
y.shape
# 3 categorical

(150, 3)

In [ ]:
y

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [ ]:
 from sklearn.model_selection import train_test_split

In [ ]:
train_test_split

<function sklearn.model_selection._split.train_test_split>

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [ ]:
X_train


array([[5.7, 2.9, 4.2, 1.3],
       [7.6, 3. , 6.6, 2.1],
       [5.6, 3. , 4.5, 1.5],
       [5.1, 3.5, 1.4, 0.2],
       [7.7, 2.8, 6.7, 2. ],
       [5.8, 2.7, 4.1, 1. ],
       [5.2, 3.4, 1.4, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [5.1, 3.8, 1.9, 0.4],
       [5. , 2. , 3.5, 1. ],
       [6.3, 2.7, 4.9, 1.8],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [5.6, 2.7, 4.2, 1.3],
       [5.1, 3.4, 1.5, 0.2],
       [5.7, 3. , 4.2, 1.2],
       [7.7, 3.8, 6.7, 2.2],
       [4.6, 3.2, 1.4, 0.2],
       [6.2, 2.9, 4.3, 1.3],
       [5.7, 2.5, 5. , 2. ],
       [5.5, 4.2, 1.4, 0.2],
       [6. , 3. , 4.8, 1.8],
       [5.8, 2.7, 5.1, 1.9],
       [6. , 2.2, 4. , 1. ],
       [5.4, 3. , 4.5, 1.5],
       [6.2, 3.4, 5.4, 2.3],
       [5.5, 2.3, 4. , 1.3],
       [5.4, 3.9, 1.7, 0.4],
       [5. , 2.3, 3.3, 1. ],
       [6.4, 2.7, 5.3, 1.9],
       [5. , 3.3, 1.4, 0.2],
       [5. , 3.2, 1.2, 0.2],
       [5.5, 2.4, 3.8, 1.1],
       [6.7, 3

#**Standardizing the Data**

In [ ]:
'''Usually when using Neural Networks, you will get better performance when you standardize the data. Standardization just means 
normalizing the values to all fit between a certain range, like 0-1, or -1 to 1.
The scikit learn library also provides a nice function for this.'''
# http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.MinMaxScaler.html

In [ ]:
from sklearn.preprocessing import MinMaxScaler

In [ ]:
scaler_object = MinMaxScaler()

In [ ]:
np.array([5,10,15,20])/20

array([0.25, 0.5 , 0.75, 1.  ])

In [ ]:
scaler_object = MinMaxScaler()


In [ ]:
scaler_object.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [ ]:
scaled_X_train = scaler_object.transform(X_train)
scaled_X_test = scaler_object.transform(X_test)

In [ ]:
scaled_X_test = scaler_object.transform(X_test)

In [ ]:
scaled_X_train

array([[0.41176471, 0.40909091, 0.55357143, 0.5       ],
       [0.97058824, 0.45454545, 0.98214286, 0.83333333],
       [0.38235294, 0.45454545, 0.60714286, 0.58333333],
       [0.23529412, 0.68181818, 0.05357143, 0.04166667],
       [1.        , 0.36363636, 1.        , 0.79166667],
       [0.44117647, 0.31818182, 0.53571429, 0.375     ],
       [0.26470588, 0.63636364, 0.05357143, 0.04166667],
       [0.20588235, 0.68181818, 0.03571429, 0.08333333],
       [0.23529412, 0.81818182, 0.14285714, 0.125     ],
       [0.20588235, 0.        , 0.42857143, 0.375     ],
       [0.58823529, 0.31818182, 0.67857143, 0.70833333],
       [0.14705882, 0.63636364, 0.14285714, 0.04166667],
       [0.20588235, 0.45454545, 0.08928571, 0.04166667],
       [0.23529412, 0.59090909, 0.10714286, 0.16666667],
       [0.38235294, 0.31818182, 0.55357143, 0.5       ],
       [0.23529412, 0.63636364, 0.07142857, 0.04166667],
       [0.41176471, 0.45454545, 0.55357143, 0.45833333],
       [1.        , 0.81818182,

#**Building the Network with Keras**

In [ ]:
#Let's build a simple neural network!
from keras.models import Sequential
from keras.layers import Dense

In [ ]:
model = Sequential()
model.add(Dense(8, input_dim=4, activation='relu'))#8-nurans
model.add(Dense(8, input_dim=4, activation='relu'))#8-nurans
model.add(Dense(3, activation='softmax'))#3-nurans
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 8)                 40        
_________________________________________________________________
dense_1 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_2 (Dense)              (None, 3)                 27        
Total params: 139
Trainable params: 139
Non-trainable params: 0
_________________________________________________________________


#**Fit (Train) the Model**

In [ ]:
#Play around with number of epochs as well!
model.fit(scaled_X_train,y_train,epochs=150, verbose=2)

Epoch 1/150
4/4 - 1s - loss: 1.0491 - accuracy: 0.3500
Epoch 2/150
4/4 - 0s - loss: 1.0386 - accuracy: 0.3400
Epoch 3/150
4/4 - 0s - loss: 1.0302 - accuracy: 0.3500
Epoch 4/150
4/4 - 0s - loss: 1.0226 - accuracy: 0.3700
Epoch 5/150
4/4 - 0s - loss: 1.0144 - accuracy: 0.3700
Epoch 6/150
4/4 - 0s - loss: 1.0055 - accuracy: 0.3800
Epoch 7/150
4/4 - 0s - loss: 0.9964 - accuracy: 0.3800
Epoch 8/150
4/4 - 0s - loss: 0.9860 - accuracy: 0.4100
Epoch 9/150
4/4 - 0s - loss: 0.9749 - accuracy: 0.4500
Epoch 10/150
4/4 - 0s - loss: 0.9649 - accuracy: 0.5400
Epoch 11/150
4/4 - 0s - loss: 0.9561 - accuracy: 0.6200
Epoch 12/150
4/4 - 0s - loss: 0.9468 - accuracy: 0.6200
Epoch 13/150
4/4 - 0s - loss: 0.9378 - accuracy: 0.6400
Epoch 14/150
4/4 - 0s - loss: 0.9299 - accuracy: 0.6300
Epoch 15/150
4/4 - 0s - loss: 0.9211 - accuracy: 0.6300
Epoch 16/150
4/4 - 0s - loss: 0.9124 - accuracy: 0.6600
Epoch 17/150
4/4 - 0s - loss: 0.9042 - accuracy: 0.6700
Epoch 18/150
4/4 - 0s - loss: 0.8956 - accuracy: 0.6500
E

#**Predicting New Unseen Data**

In [ ]:
'''Let's see how we did by predicting on new data. Remember, our model has never seen the test data that we scaled previously! This process is
the exact same process you would use on totally brand new data. For example , a brand new bank note that you just analyzed .'''

"Let's see how we did by predicting on new data. Remember, our model has never seen the test data that we scaled previously! This process is\nthe exact same process you would use on totally brand new data. For example , a brand new bank note that you just analyzed ."

In [ ]:
scaled_X_test

array([[ 0.52941176,  0.36363636,  0.64285714,  0.45833333],
       [ 0.41176471,  0.81818182,  0.10714286,  0.08333333],
       [ 1.        ,  0.27272727,  1.03571429,  0.91666667],
       [ 0.5       ,  0.40909091,  0.60714286,  0.58333333],
       [ 0.73529412,  0.36363636,  0.66071429,  0.54166667],
       [ 0.32352941,  0.63636364,  0.07142857,  0.125     ],
       [ 0.38235294,  0.40909091,  0.44642857,  0.5       ],
       [ 0.76470588,  0.5       ,  0.71428571,  0.91666667],
       [ 0.55882353,  0.09090909,  0.60714286,  0.58333333],
       [ 0.44117647,  0.31818182,  0.5       ,  0.45833333],
       [ 0.64705882,  0.54545455,  0.71428571,  0.79166667],
       [ 0.14705882,  0.45454545,  0.05357143,  0.        ],
       [ 0.35294118,  0.68181818,  0.03571429,  0.04166667],
       [ 0.17647059,  0.5       ,  0.07142857,  0.        ],
       [ 0.23529412,  0.81818182,  0.07142857,  0.08333333],
       [ 0.58823529,  0.59090909,  0.64285714,  0.625     ],
       [ 0.64705882,  0.

In [ ]:
model.predict(scaled_X_test)

array([[3.5234801e-02, 6.8682045e-01, 2.7794468e-01],
       [9.5390815e-01, 4.4759136e-02, 1.3326936e-03],
       [4.7660531e-05, 7.5700074e-02, 9.2425227e-01],
       [2.1534197e-02, 5.8315802e-01, 3.9530778e-01],
       [6.8325959e-03, 4.7298557e-01, 5.2018183e-01],
       [9.1789919e-01, 7.8422129e-02, 3.6786781e-03],
       [9.0958476e-02, 6.9086027e-01, 2.1818124e-01],
       [3.5016637e-04, 1.3438644e-01, 8.6526334e-01],
       [2.6996483e-03, 2.7999857e-01, 7.1730173e-01],
       [5.6584626e-02, 6.7556316e-01, 2.6785225e-01],
       [2.9158229e-03, 3.3254951e-01, 6.6453469e-01],
       [9.5311117e-01, 4.4846665e-02, 2.0421906e-03],
       [9.5824414e-01, 4.0376011e-02, 1.3798656e-03],
       [9.5778042e-01, 4.0544156e-02, 1.6754552e-03],
       [9.7551662e-01, 2.3892296e-02, 5.9114856e-04],
       [2.4297865e-02, 6.3373774e-01, 3.4196439e-01],
       [5.3351262e-04, 1.7984572e-01, 8.1962079e-01],
       [6.4174213e-02, 6.7665881e-01, 2.5916702e-01],
       [4.6905931e-02, 6.841

In [ ]:
# Spits out probabilities by default.
# model.predict(scaled_X_test)

In [ ]:
model.predict_classes(scaled_X_test)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


array([1, 0, 2, 1, 2, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 1, 2, 1, 2])

In [ ]:
y_test

array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0

In [ ]:
predictions = model.predict_classes(scaled_X_test)

In [ ]:
y_test.argmax(axis=1)

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2])

In [ ]:
y_test

array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0

#**Evaluating Model Performance**

In [ ]:
'''So how well did we do? How do we actually measure "well". Is 95% accuracy good enough? It all depends on the situation. Also we need to take
into account things like recall and precision. Make sure to watch the video discussion on classification evaluation before running this code!'''

In [ ]:
model.metrics_names

['loss', 'accuracy']

In [ ]:
model.evaluate(x=scaled_X_test,y=y_test)

2/2 [==============================] - 0s 5ms/step - loss: 0.2658 - accuracy: 0.9400


[0.26583927869796753, 0.9399999976158142]

In [ ]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score


In [ ]:
predictions = model.predict_classes(scaled_X_test)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


In [ ]:
predictions

array([1, 0, 2, 1, 2, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 1, 2, 1, 2])

In [ ]:
y_test.argmax(axis=1)

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2])

In [ ]:
confusion_matrix(y_test.argmax(axis=1),predictions)

array([[19,  0,  0],
       [ 0, 13,  2],
       [ 0,  1, 15]])

In [ ]:
print(classification_report(y_test.argmax(axis=1),predictions))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       0.93      0.87      0.90        15
           2       0.88      0.94      0.91        16

    accuracy                           0.94        50
   macro avg       0.94      0.93      0.94        50
weighted avg       0.94      0.94      0.94        50



In [ ]:
accuracy_score(y_test.argmax(axis=1),predictions)

0.94

#**Saving and Loading Models**

In [ ]:
#Now that we have a model trained, let's see how we can save and load it.

In [ ]:
model.save('myfirstmodel.h5')

In [ ]:
from keras.models import load_model

In [ ]:
newmodel = load_model('myfirstmodel.h5')

In [ ]:
newmodel.predict_classes(X_test)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


array([2, 1, 2, 2, 2, 1, 2, 2, 2, 2, 2, 1, 1, 1, 1, 2, 2, 2, 2, 2, 1, 2,
       1, 2, 2, 2, 2, 2, 1, 1, 1, 1, 2, 1, 1, 2, 2, 1, 1, 1, 2, 2, 2, 1,
       1, 2, 2, 2, 2, 2])

In [ ]:
#Great job! You now know how to preprocess data, train a neural network, and evaluate its classification performance!

#**Recurrent Neural Networks Theory**

In [ ]:
#Examples of sequences
 # 1 Time Series Data (Sales)
 # 2 Sentences
 # 3 Audio
 # 4 Car Trajetories
 # 5 Music
 

In [ ]:
#Let's imagine a sequence:
 [1,2,3,4,5,6]
 -> Would you be able to predict a similar sequence shifted one time step into the future?
  -> [2,3,4,5,6,7]

In [ ]:
'''-> Cells that are a function of inputs from previous time steps are also known as memory cell.
   -> RNN are also flexible in their inputs and outputs for both sequences and single vector values.
   we can also create entire layers of recurrent neurons'''

In [ ]:
'''RNN are also very flexible in their input and outputs
Let's see a few examples.
Now that we understand basic RNNs move on to understanding a particular cell structure known as LSTM(Long Term Memory Units).'''


#**LSTM AND GRU**